/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Size = "xs" | "sm" | "md" | "lg" | "xl" | "2xl";

export interface Country {
  id: string;
  title: string;
  thumbnail?: {
    src: string;
    alt: string;
  };
  blocks?: (Mdx | ArticleEmbed | ArticleCarouselEmbed)[];
  info?: {
    label: string;
    value: string;
  }[];
  ways?: string[];
}
export interface Mdx {
  type: "mdx";
  content: string;
}
export interface ArticleEmbed {
  type: "articleEmbed";
  slug: string;
  mb?: Size;
}
export interface ArticleCarouselEmbed {
  type: "articleCarouselEmbed";
  slugs: string[];
  mb?: Size;
}
