/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type TextColor =
  | "auto"
  | "inherit"
  | "white"
  | "black"
  | "gray90"
  | "gray70"
  | "gray30"
  | "gray20"
  | "blue"
  | "blue30"
  | "darkBlue"
  | "darkBlue60"
  | "darkBlue40"
  | "spaceBlue"
  | "lightBlue"
  | "red"
  | "pink"
  | "purple"
  | "orange";
export type Size = "xs" | "sm" | "md" | "lg" | "xl" | "2xl";
export type Color =
  | "auto"
  | "inherit"
  | "white"
  | "black"
  | "gray90"
  | "gray70"
  | "gray30"
  | "gray20"
  | "blue"
  | "blue30"
  | "darkBlue"
  | "darkBlue60"
  | "darkBlue40"
  | "spaceBlue"
  | "lightBlue"
  | "red"
  | "pink"
  | "purple"
  | "orange"
  | "primaryGradient";
export type StoriesList = {
  steps: {
    url?: string;
    poster?: string;
    alt?: string;
    mdx?: string;
    duration?: number;
    background?: string;
    overlayBackground?: string;
    textColor?: TextColor;
    padding?: string;
    margin?: string;
    maxWidth?: Size;
    justify?: "start" | "center" | "end";
    align?: "stretch" | "start" | "center" | "end";
  }[];
  label?: string;
  labelLines?: number;
  labelColor?: Color;
  loop?: boolean;
  crossColor?: Color;
  textColor?: TextColor;
  posterIndex?: number;
  duration?: number;
  background?: string;
  overlayBackground?: string;
  padding?: string;
  margin?: string;
  maxWidth?: Size;
  justify?: "start" | "center" | "end";
  align?: "stretch" | "start" | "center" | "end";
}[];
