/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Way {
  id: string;
  title: string;
  description?: string;
  info?: {
    label: string;
    value?: string;
    cols?: 1 | 2;
    lines?: number;
    topImage?: {
      src: string;
      alt: string;
    };
    leftImage?: {
      src: string;
      alt: string;
    };
  }[];
}
